export const resume = {
  frontSkills: [
    [
      'Typescript',
      'Javascript',
      'JEST',
      'OOP',
      'Functional Programming',
      'Design Patterns',
    ],
    ['React', 'Vue', 'NextJS', 'NuxtJS', 'Redux', 'Vuex'],
    ['React Native', 'Flutter'],
    ['Node JS', 'Deno', 'MERN', 'Apollo', 'GraphQL', 'SocketIO'],
    ['Npm', 'Yarn', 'Webpack'],
    ['HTML', 'CSS', 'SASS', 'Bootstrap', 'Material-UI', 'Vuetify', 'Gulp'],
  ],
  backSkills: [
    ['Python', 'Django', 'Django', 'Rest Framework', 'Flask'],
    ['PHP', 'Yii', 'Laravel'],
    [
      'Machine Learning',
      'Neural Networks',
      'TensorFlow',
      'Keras',
      'Google Cloud GPUs',
    ],
    ['Data Analysis', 'Pandas', 'SciPy', 'SciKit-Learn', 'NLTK'],
    ['Data Collection:', 'Scrapy', 'BeautifulSoup'],
    ['Object Detection', 'Face recognition', 'Image Classification'],
    ['Pillow', 'OpenCV', 'Matplotlib', 'Anaconda'],
  ],
  dbSkills: [
    ['SQL advanced', 'MySQL', 'PostgreSQL', 'SQLite'],
    ['Elasticsearch', 'MongoDB', 'FireBase'],
    ['Big DB performance optimization'],
    ['SQLAlchemy', 'DjangoORM', 'Peewee'],
  ],
  osSkills: [],
  marketingSkills: [],
  generalSkills: [],
  otherSkills: [],
  ide: [],
};
